apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: default
spec:
  ports:
  - nodePort: 30442 # 30000 - 302222
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: node-app
  type: NodePort
